# Generated by Django 6.1.1 on 2026-09-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_cnpj_cpf_alter_client_email_and_more'),
        ('sales', '0002_csvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('client', 'order_number')},
        ),
    ]
